baseurl = "https://assets.janoticketing.co.uk/"
languageCode = "en-GB"
languageLang = "en"
title = "Jano Ticketing"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[menu]
  [[menu.main]]
    identifier = "community"
    name = "Community"
    url = "#"
    weight = 900
  [[menu.main]]
    identifier = "repo"
    parent = "community"
    name = "Module Repository"
    url = "https://repo.janoticketing.co.uk"
    weight = 10
  [[menu.main]]
    identifier = "forum"
    parent = "community"
    name = "Forum"
    url = "https://forum.janoticketing.co.uk"
    weight = 11
  [[menu.main]]
    identifier = "blog"
    parent = "community"
    name = "Blog"
    url = "/blog/"
    weight = 15
