baseurl = "/"
languageCode = "en-GB"
languageLang = "en"
title = "Jano Ticketing"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[menu]
  [[menu.main]]
    identifier = "Docs"
    name = "Docs"
    url = "/docs/"
    weight = -998
  [[menu.main]]
    identifier = "Community"
    name = "Community"
    url = "#"
    weight = 900
  [[menu.main]]
    identifier = "Repo"
    parent = "Community"
    name = "Module Repository"
    url = "https://repo.janoticketing.co.uk"
    weight = 10
  [[menu.main]]
    identifier = "Forum"
    parent = "Community"
    name = "Forum"
    url = "https://forum.jano.rocks"
    weight = 11
  [[menu.main]]
    identifier = "Blog"
    parent = "Community"
    name = "Blog"
    url = "/blog/"
    weight = 15
  [[menu.docs]]
    identifier = "GettingStarted"
    name = "Getting Started"
    url = "/docs/getting-started/"