backend:
  name: github
  repo: jano-may-ball/janoticketing.co.uk
media_folder: "site/static/images/uploads"
collections:
- name: "blog"
  label: "Blog"
  folder: "site/content/blog"
  fields:
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ"}
  - {label: "Draft", name: "draft", widget: "boolean"}
  - {label: "Content", name: "body", widget: "markdown"}
